name: ragapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.3
  firebase_messaging: 6.0.16
  flutter_local_notifications: 1.4.4
  firebase_storage: 3.1.6
  agora_rtc_engine: 1.0.13
  http: ^0.12.0+4
  path_provider: ^1.6.1
  shared_preferences: ^0.5.6+2
  rxdart: ^0.23.1
  provider: 4.1.2
  cached_network_image: 2.2.0+1
  animations: 1.1.0
  cloud_firestore: 0.13.6
  simple_animations: 2.2.1
  google_sign_in: 4.5.1
  firebase_auth: 0.16.1
  date_format: 1.0.8
  firebase_core: 0.4.4
  flutter_screenutil: 1.1.0
  image_picker: 0.6.7+2
  image_cropper: 1.2.3
  palette_generator: 0.2.3
  permission_handler: ^5.0.1+1
  url_launcher: 5.4.11
  animate_do: 1.7.2
  flutter_youtube: 2.0.0
  flutter_inner_drawer: 0.5.2
  photo_view: 0.9.2
  timeago: 2.0.26
  file_picker: ^1.5.0+2
  sliding_up_panel: ^1.0.2
  flutter_markdown: 0.4.2
  markdown_editable_textinput: 1.0.0
  flutter_facebook_login: 3.0.0
  show_more_text_popup: 0.2.0
  image_downloader: 0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/logonotificacion.png
    - images/facebook.png
    - images/google.png
    - icons/twitter.png
    - icons/facebook.png
    - icons/instagram.png
    - icons/youtube.png
    - icons/home.png
    - icons/streaming.png
    - icons/menu.png
    - icons/servidores.png
    - icons/contacto.png
    - icons/altar.png
    - icons/administrador.png
    - icons/youtubeColor.png
    - icons/anuncio.png
    - icons/notificacion.png
    - icons/ministerio.png
    - icons/ajustes.png
    - icons/comentario.png
    - icons/compartir.png
    - icons/live.png
    - icons/notificationBell.png

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Black.ttf
        - asset: fonts/Nunito/Nunito-BlackItalic.ttf
        - asset: fonts/Nunito/Nunito-Bold.ttf
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito/Nunito-ExtraBoldItalic.ttf
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito/Nunito-ExtraLightItalic.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
        - asset: fonts/Nunito/Nunito-Light.ttf
        - asset: fonts/Nunito/Nunito-LightItalic.ttf
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
        - asset: fonts/Nunito/Nunito-SemiBoldItalic.ttf

    - family: Glenn Slab
      fonts:
        - asset: fonts/Glenn Slab/BwGlennSlab-Black.otf
        - asset: fonts/Glenn Slab/BwGlennSlab-Bold.otf
        - asset: fonts/Glenn Slab/BwGlennSlab-ExtraBold.otf
        - asset: fonts/Glenn Slab/BwGlennSlab-Hairline.otf
        - asset: fonts/Glenn Slab/BwGlennSlab-Light.otf
        - asset: fonts/Glenn Slab/BwGlennSlab-Medium.otf
        - asset: fonts/Glenn Slab/BwGlennSlab-Thin.otf